DEFAULT_SETTINGS = {
    "preconditions": {
        "os": "windows",
        "resolution": "1920x1080",
        "scaling": 100,
        "game_mode": "windowed",
        "chat_minimized": False,
        "verified": False
    },
    "auth": {"id": "", "password": ""},
    "hotkeys": {
        "start": "f1",
        "stop": "f2",
        "hp_potion": "del",
        "mp_potion": "end",
        "attack": "ctrl",
        "jump": "d",
        "loot": "z",
        "key_down_time": 4.5,
        "attack_delay": 0.5
    },
    "combat": {"skill_sequence": ["ctrl"], "skill_delay_ms": 200},
    "potion": {"hp_threshold": 50, "mp_threshold": 30, "hp_potion_key": "del", "mp_potion_key": "end"},
    "vision": {
        "mob_templates_path": "assets/mob_templates",
        "ui_elements_path": "assets/ui_elements",
        "assets_path": "assets",
        "nickname_template": "settings/nickname.png",
        "nickname_threshold": 0.8,
        "lie_template": "assets/ui_elements/polygraph.png",
        "lie_threshold": 0.7,
        "enemy_template": "assets/ui_elements/enemy_alert.png",
        "enemy_threshold": 0.7,
        "chat_region": [10, 800, 400, 200],
        "chat_color_tolerance": 30,
        "chat_pixel_ratio": 0.002,
        "chat_colors": {"whisper": "#ff99ff", "normal": "#ffffff", "party": "#00ffcc"},
        "other_user_template": "assets/ui_elements/other_user.png",
        "other_user_threshold": 0.75
    },
    "movement": {"speed_factor": 117},
    "monsters": [
        "leftjoo.png",
        "rightjoo.png",
        "leftblue.png",
        "rightblue.png",
        "leftslime.png",
        "rightslime.png",
        "leftstump.png",
        "rightstump.png",
        "leftgreen.png",
        "rightgreen.png",
        "rightred.png",
        "leftred.png",
        "leftgreenbu.png",
        "rightgreenbu.png",
        "joo3.png",
        "joo1.png",
        "joo2.png",
        "slime.png",
        "slime2.png",
        "stump.png",
        "greenbu.png",
        "greenbu2.png"
    ],
    "monster_settings": {"nickname_recognition_rate": 0.8, "monster_recognition_rate": 0.8, "x_range": 200, "y_range": 60, "handle_opposite": True},
    "routes": [],
    "buffs": [],
    "misc": {
        "hp_potion_percent": 50,
        "mp_potion_percent": 30,
        "handle_opposite": True,
        "clear_remain": True,
        "lie_detector": True,
        "enemy_detector": True,
        "chat_detector": True,
        "other_user_detector": True,
        "user_detect": True,
        "user_detect_time": 10,
        "stationary": False,
        "stationary_direction": "right",
        "stationary_time": 30
    },
    "ui": {"language": "en", "theme": "dark"},
    "debug": {"enable_debug": False, "simulation_mode": False}
}
